#!/usr/bin/python3 -B

import sys
from optparse import OptionParser
from cyshell import CypressShell

cysh = CypressShell()

parser = OptionParser()
parser.add_option("-f", "--fpga", action="store", type="choice", dest="fpga", choices=['spartan', 'artix'], help="FPGA USB channel (spartan, artix)")
(options, args) = parser.parse_args()

if options.fpga is None:
   parser.print_help()
   sys.exit(1)

if options.fpga == 'spartan':
   cysh.open(1)
elif options.fpga == 'artix':
   cysh.open(0)

cysh.cmdloop()
